version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: lumina_db
    restart: always
    environment:
      POSTGRES_USER: lumina_user
      POSTGRES_PASSWORD: lumina_password
      POSTGRES_DB: lumina_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
